# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI_CD_tets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm run dev
    - run: npm run build

    - name: Upload and deploy on the server using SSH
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@f2f261e6bd55fc750ceb9b0b7e49ad0ef72a7780
      uses: easingthemes/ssh-deploy@v3.0.1
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: ' -avzr --delete'
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: 'root'
        # Source directory
        SOURCE: 'dist'
        # Target directory
        TARGET: /www/wwwroot/xsd666.top/ci_cd
